[package]
name = "wgpu-test"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.5.1", features = ["derive"] }
cgmath = "0.18"
egui = "0.13"
egui_wgpu_backend = "0.11"
egui_winit_platform = "0.9"
env_logger = "0.9"
image = "0.23"
log = "0.4"
pollster = "0.2.0"
wgpu = "0.10"
winit = "0.25"
